{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from choice_model import ChoiceModel\n",
    "\n",
    "folder = 'orig_graph'\n",
    "\n",
    "def predict(period):\n",
    "    model = ChoiceModel()\n",
    "    prev_period_file = f'{folder}/{folder}_{period-1}.pkl'\n",
    "    new_model = ChoiceModel(graph_path=prev_period_file) \n",
    "    graph = model.get_period(period)\n",
    "    new_nodes = [n for n in graph.nodes if n not in list(new_model.graph.nodes)]\n",
    "    # new_nodes = [n for n in new_nodes if graph.nodes[n]['type'] != 'Long-term Project']\n",
    "    test_graph = new_model.graph.copy()\n",
    "    test_graph = model.predict_links(test_graph, new_nodes, file_name=f\"{folder}/{folder}_{period}.pkl\",period=period)\n",
    "    new_model = ChoiceModel(graph_path=f\"{folder}/{folder}_{period}.pkl\")\n",
    "    issolated_nodes = new_model.get_isolated_nodes()\n",
    "    if len(issolated_nodes) > 0:\n",
    "        test_graph = new_model.graph.copy()\n",
    "        test_graph = model.predict_links(test_graph, issolated_nodes,file_name=f\"{folder}/{folder}_{period}.pkl\",k1=10,k2=5,top_k=None)\n",
    "        new_model.remove_isolated_nodes()\n",
    "    new_model.visualize(file_name=f\"{folder}/{folder}_{period}.html\")\n",
    "    PPI, CVI, DCI = new_model.evaluate(test_graph)\n",
    "    print(f\"Period {period} PPI: {PPI} CVI: {CVI} DCI: {DCI}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 76/76 [00:00<00:00, 659.64it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ecd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf2e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfcd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfdc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bffd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d15e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45eb80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c437670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ee50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf6a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c437280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ef70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfaf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c437250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ebb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c437400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ef40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4371c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bffa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ea60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45eac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfdc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447d30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf7c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45eb50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16c0f8f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfa30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfb20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4477f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Period 1 PPI: 0.31012110726643594 CVI: 2.843137254901961 DCI: 0.058823529411764705\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  0%|          | 0/136 [00:00<?, ?it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1fa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 136/136 [00:00<00:00, 1116.85it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfe50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfd60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfd00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c96a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9d60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9d00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4474c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16c0f8ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cffd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf7c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb4f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf4c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfe20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf9a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfaf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfe80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16c0f8f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfd60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16c0f8f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbeb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cba30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb7c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17ac2be20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c98b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfdf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfc40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45edf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9d00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbeb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c96d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16c0f8f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d10d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45edf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c98e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16c0f8e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f875250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb4f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d68e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c92b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45efa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f8751f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9d60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfd30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f875be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf9a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f875730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Period 2 PPI: 0.31012110726643594 CVI: 2.843137254901961 DCI: 0.058823529411764705\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 99%|█████████▊| 209/212 [00:00<00:00, 1047.49it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bffd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45edf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c96a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfc10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c97f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfa90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d69d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45eca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c92b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d64c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1d60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45edf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf9a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9d30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45eac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfd90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf0a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbd60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfd00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c27c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfb20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c27f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbf40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf7c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfe80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbd90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbaf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cba90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfdc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d64f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c22e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45edf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbe50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbb50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbbb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c26a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6af0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbfd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbf10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbe20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ebb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbd60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ec40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb9a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ec70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c37f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c23d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c21f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45eaf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ee50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfeb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2640>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9f40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3e80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6fa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfdf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ec10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3790>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c23d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfb50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ef70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6fa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfbb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ee50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cffd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9fa0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ef10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45edc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c32b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9af0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c20a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983c7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9a30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e460>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983c400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c93d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ef70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ed90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983c3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9d00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ee20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983c580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ed90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfd30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfc10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89eac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d1fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb0a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfa00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf490>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c3dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 212/212 [00:00<00:00, 1032.28it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbc40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfb50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Period 3 PPI: 0.31012110726643594 CVI: 2.843137254901961 DCI: 0.058823529411764705\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  0%|          | 0/123 [00:00<?, ?it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ea90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c21c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfeb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfcd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ea60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ee20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ed30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89eb50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89eb20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c27f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c96d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c21f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e8e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4479d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf8e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c23d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89eb50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45eac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bfdc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740c9580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e4c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfdc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ec10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cbdc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf250>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ebb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ef70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf1f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89eb20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45e4c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983c850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e610>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb280>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x309b6c160>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e730>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e0a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf9a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ebb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ef70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf400>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e0a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4472b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c20d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983cc10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x309b6caf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfe80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45eeb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x309b6c700>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89eca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c25e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983ceb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x309b6cb50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89edf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfbb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c45ec10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x309b6c880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cf580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c24c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983ce20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x309b6ca90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983cb20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d69d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 123/123 [00:00<00:00, 1110.94it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bf970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983c880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89ef10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c447910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4cfd60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f89e970>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983c2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17f5c2190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6880>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1740cb220>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4bff70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6a90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17c4d6e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x30983cc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Period 4 PPI: 0.31012110726643594 CVI: 2.843137254901961 DCI: 0.058823529411764705\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "for i in range(1,5):\n",
    "    predict(i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pytorch",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
