{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "editable": true,
    "slideshow": {
     "slide_type": ""
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saving graph to sim_data_2/sim_data_2_0.pkl\n"
     ]
    }
   ],
   "source": [
    "from choice_model import ChoiceModel\n",
    "import os\n",
    "\n",
    "folder = 'sim_data_2'\n",
    "base_url = 'http://localhost:11434'\n",
    "remove_type = None\n",
    "\n",
    "# remove_type = 'Organization'\n",
    "\n",
    "if not os.path.exists(folder):\n",
    "    os.makedirs(folder)\n",
    "\n",
    "old_model = ChoiceModel(base_url=base_url)\n",
    "old_model.roll_back(0)\n",
    "init_graph = old_model.graph.copy()\n",
    "nodes = [n for n in init_graph.nodes if init_graph.nodes[n]['type'] != remove_type]\n",
    "test_graph = init_graph.subgraph(nodes).copy()\n",
    "old_model.save_graph(graph=test_graph, file_name=f\"{folder}/{folder}_0.pkl\")\n",
    "old_model.visualize(graph=test_graph, file_name=f\"{folder}/{folder}_0.html\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "editable": true,
    "slideshow": {
     "slide_type": ""
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "from choice_model import ChoiceModel\n",
    "import networkx as nx\n",
    "\n",
    "folder = 'sim_data_2'\n",
    "base_url = 'http://10.29.179.254/:11434'\n",
    "remove_type = None\n",
    "\n",
    "def predict(period,remove_type=None, k1=5,k2=1,top_k=10):\n",
    "    model = ChoiceModel(base_url=base_url)\n",
    "    if period == 0:\n",
    "        test_graph = nx.DiGraph()\n",
    "    else:\n",
    "        prev_period_file = f'{folder}/{folder}_{period-1}.pkl'\n",
    "        new_model = ChoiceModel(graph_path=prev_period_file,base_url=base_url) \n",
    "        test_graph = new_model.graph.copy()\n",
    "\n",
    "    graph = model.get_period(period)\n",
    "    new_nodes = [n for n in graph.nodes if n not in list(test_graph.nodes)]\n",
    "    new_nodes = [n for n in new_nodes if graph.nodes[n]['type'] != remove_type]\n",
    "    \n",
    "    print(\"begin simulation\",len(test_graph.nodes),len(test_graph.edges))\n",
    "    test_graph,failed_nodes = model.predict_links(test_graph, new_nodes, file_name=f\"{folder}/{folder}_{period}.pkl\",\n",
    "                                     choice_type=None,k1=k1,k2=k2,top_k=top_k,period=period)\n",
    "    \n",
    "    if len(failed_nodes) > 0:\n",
    "        print(\"retrying failed nodes\")\n",
    "        test_graph,_ = model.predict_links(test_graph, failed_nodes, file_name=f\"{folder}/{folder}_{period}.pkl\",\n",
    "                                     choice_type=None,k1=k1,k2=k2,top_k=top_k,period=period)\n",
    "\n",
    "    # issolated_nodes = model.get_isolated_nodes(graph=test_graph)\n",
    "    # if len(issolated_nodes) > 0:\n",
    "    #     print(\"retrying issolated nodes\")\n",
    "    #     test_graph,_ = model.predict_links(test_graph, issolated_nodes, file_name=f\"{folder}/{folder}_{period}.pkl\",\n",
    "    #                                  choice_type=None,k1=k1,k2=k2,top_k=top_k,period=period)\n",
    "    #     test_graph = model.remove_isolated_nodes(graph=test_graph)\n",
    "    #     model.save_graph(file_name=f\"{folder}/{folder}_{period}.pkl\",graph=test_graph)\n",
    "\n",
    "    model.save_graph(file_name=f\"{folder}/{folder}_{period}.pkl\",graph=test_graph)\n",
    "    new_model = ChoiceModel(graph_path=f\"{folder}/{folder}_{period}.pkl\")\n",
    "    new_model.visualize(file_name=f\"{folder}/{folder}_{period}.html\")\n",
    "    print(\"end simulation\",len(test_graph.nodes),len(test_graph.edges))\n",
    "    PPI, CVI, DCI = new_model.evaluate(test_graph)\n",
    "    print(f\"Period {period} PPI: {PPI} CVI: {CVI} DCI: {DCI}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "editable": true,
    "slideshow": {
     "slide_type": ""
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "begin simulation 0 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 1953.52it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536ea7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53726450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53713210>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53710710>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53724690>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d56dc4c10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d537135d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53705ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53707190>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d56c20910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d537106d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53711350>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53725cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53704f90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53724ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53726650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d537138d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53712410>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536e9d50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f0410>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d55019150>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53753a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53727190>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53712610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53713910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53706790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53710090>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53726ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53727a50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536e9a50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53704390>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d56c21690>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e1411d250>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53725990>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53725c90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53713510>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5501b6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53726ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53725990>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53711410>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53753950>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53704fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d55019150>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536e9d90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535af3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53706590>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d537108d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53724a10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53727650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53712fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53726e10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53750450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53707410>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53707250>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536e98d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53706b10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53707d10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53713990>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53724a10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f24d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53711110>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53713990>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53750450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53706290>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53707e90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f3510>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d537525d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53705890>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53726a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53711d50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f3110>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d571367d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53711c50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53727610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53706650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5507ce10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53492290>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53752a50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53727950>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d537079d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f25d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53710ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53492690>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d537065d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53725e50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536eb7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f0710>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53490e90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5507c410>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d55061a10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f0550>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f2e10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d537279d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53705c10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53725650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53724a10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d550431d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f38d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f3350>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53706650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536f04d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Saving graph to sim_data_2/sim_data_2_0.pkl\n",
      "retrying failed nodes\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 2017.67it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53486490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53485a10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536264d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536253d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345d3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53626150>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53624250>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53627a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53485b10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53487cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345ef90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53484fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53485890>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53627850>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53627b10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345fb10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53490850>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53627190>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53625990>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53484b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53484310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535fe110>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53624950>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536245d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53627e10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345e350>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345f790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d534846d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d56b6cad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345e050>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345f990>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53626d50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53627050>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53486010>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53625310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536248d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345fa10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345db90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53484d90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d56c6bc90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345e510>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345ff10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d534873d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53624650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535fe9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53625f90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53624890>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345e450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345c810>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d534873d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d534935d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345cb10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345d810>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345cfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53487a50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53627ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535fea10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53626a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53490790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345c890>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345d450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d58425a50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53485150>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345d310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345d1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345c650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53626250>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535ffe90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53493690>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d536251d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345edd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345c110>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53486a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535fc450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345ea10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345cfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345e290>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df76239d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53627a50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535fc690>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53626f10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53485290>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345df50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345f450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535fd610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345c250>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345d790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345ea50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53486090>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53625610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535e9750>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345d3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345fcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535ffa50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535fc310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d53487390>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535fea90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d535ff410>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345c290>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error raised by inference endpoint: HTTPConnectionPool(host='10.29.179.254', port=80): Max retries exceeded with url: /:11434/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5345d410>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Saving graph to sim_data_2/sim_data_2_0.pkl\n",
      "Saving graph to sim_data_2/sim_data_2_0.pkl\n",
      "end simulation 0 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "/opt/conda/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.\n",
      "  return _methods._mean(a, axis=axis, dtype=dtype,\n",
      "/opt/conda/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide\n",
      "  ret = ret.dtype.type(ret / rcount)\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "zero-size array to reduction operation maximum which has no identity",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m i \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(\u001b[38;5;241m0\u001b[39m,\u001b[38;5;241m10\u001b[39m):\n\u001b[0;32m----> 2\u001b[0m     \u001b[43mpredict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mi\u001b[49m\u001b[43m,\u001b[49m\u001b[43mremove_type\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mremove_type\u001b[49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[0;32mIn[2], line 42\u001b[0m, in \u001b[0;36mpredict\u001b[0;34m(period, remove_type, k1, k2, top_k)\u001b[0m\n\u001b[1;32m     40\u001b[0m new_model\u001b[38;5;241m.\u001b[39mvisualize(file_name\u001b[38;5;241m=\u001b[39m\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfolder\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfolder\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m_\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mperiod\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.html\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     41\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mend simulation\u001b[39m\u001b[38;5;124m\"\u001b[39m,\u001b[38;5;28mlen\u001b[39m(test_graph\u001b[38;5;241m.\u001b[39mnodes),\u001b[38;5;28mlen\u001b[39m(test_graph\u001b[38;5;241m.\u001b[39medges))\n\u001b[0;32m---> 42\u001b[0m PPI, CVI, DCI \u001b[38;5;241m=\u001b[39m \u001b[43mnew_model\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mevaluate\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtest_graph\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     43\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPeriod \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mperiod\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m PPI: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mPPI\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m CVI: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mCVI\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m DCI: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mDCI\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/work/eggy/choice_model.py:430\u001b[0m, in \u001b[0;36mChoiceModel.evaluate\u001b[0;34m(self, graph)\u001b[0m\n\u001b[1;32m    428\u001b[0m PPI \u001b[38;5;241m=\u001b[39m cal_PPI()\n\u001b[1;32m    429\u001b[0m CVI \u001b[38;5;241m=\u001b[39m cal_CVI()\n\u001b[0;32m--> 430\u001b[0m DCI \u001b[38;5;241m=\u001b[39m \u001b[43mcal_DCI\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    432\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m PPI, CVI, DCI\n",
      "File \u001b[0;32m~/work/eggy/choice_model.py:423\u001b[0m, in \u001b[0;36mChoiceModel.evaluate.<locals>.cal_DCI\u001b[0;34m()\u001b[0m\n\u001b[1;32m    421\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mcal_DCI\u001b[39m():\n\u001b[1;32m    422\u001b[0m     degrees \u001b[38;5;241m=\u001b[39m [graph\u001b[38;5;241m.\u001b[39mdegree(a) \u001b[38;5;28;01mfor\u001b[39;00m a \u001b[38;5;129;01min\u001b[39;00m actors]\n\u001b[0;32m--> 423\u001b[0m     MAX \u001b[38;5;241m=\u001b[39m \u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmax\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdegrees\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    424\u001b[0m     Q2 \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39mpercentile(degrees, \u001b[38;5;241m50\u001b[39m)\n\u001b[1;32m    425\u001b[0m     DCI \u001b[38;5;241m=\u001b[39m Q2\u001b[38;5;241m/\u001b[39mMAX\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/numpy/core/fromnumeric.py:2810\u001b[0m, in \u001b[0;36mmax\u001b[0;34m(a, axis, out, keepdims, initial, where)\u001b[0m\n\u001b[1;32m   2692\u001b[0m \u001b[38;5;129m@array_function_dispatch\u001b[39m(_max_dispatcher)\n\u001b[1;32m   2693\u001b[0m \u001b[38;5;129m@set_module\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mnumpy\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m   2694\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mmax\u001b[39m(a, axis\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m, out\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m, keepdims\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39m_NoValue, initial\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39m_NoValue,\n\u001b[1;32m   2695\u001b[0m          where\u001b[38;5;241m=\u001b[39mnp\u001b[38;5;241m.\u001b[39m_NoValue):\n\u001b[1;32m   2696\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m   2697\u001b[0m \u001b[38;5;124;03m    Return the maximum of an array or maximum along an axis.\u001b[39;00m\n\u001b[1;32m   2698\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   2808\u001b[0m \u001b[38;5;124;03m    5\u001b[39;00m\n\u001b[1;32m   2809\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m-> 2810\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_wrapreduction\u001b[49m\u001b[43m(\u001b[49m\u001b[43ma\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmaximum\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mmax\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maxis\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   2811\u001b[0m \u001b[43m                          \u001b[49m\u001b[43mkeepdims\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mkeepdims\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minitial\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43minitial\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mwhere\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mwhere\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/numpy/core/fromnumeric.py:88\u001b[0m, in \u001b[0;36m_wrapreduction\u001b[0;34m(obj, ufunc, method, axis, dtype, out, **kwargs)\u001b[0m\n\u001b[1;32m     85\u001b[0m         \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     86\u001b[0m             \u001b[38;5;28;01mreturn\u001b[39;00m reduction(axis\u001b[38;5;241m=\u001b[39maxis, out\u001b[38;5;241m=\u001b[39mout, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mpasskwargs)\n\u001b[0;32m---> 88\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mufunc\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mreduce\u001b[49m\u001b[43m(\u001b[49m\u001b[43mobj\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maxis\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdtype\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mpasskwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[0;31mValueError\u001b[0m: zero-size array to reduction operation maximum which has no identity"
     ]
    }
   ],
   "source": [
    "for i in range(0,10):\n",
    "    predict(i,remove_type=remove_type)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
